// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5HakwOgMCnsVmHXhyaGNt5d8pcWAXqRY',
    appId: '1:637146499788:web:cadfda53b55b59498b9069',
    messagingSenderId: '637146499788',
    projectId: 'chatterbox-fcd7c',
    authDomain: 'chatterbox-fcd7c.firebaseapp.com',
    storageBucket: 'chatterbox-fcd7c.appspot.com',
    measurementId: 'G-BCGVNE3RXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-g8cU6ojj_DrhPmZWtNN1B574qyM41S0',
    appId: '1:637146499788:android:279490675e5922d98b9069',
    messagingSenderId: '637146499788',
    projectId: 'chatterbox-fcd7c',
    storageBucket: 'chatterbox-fcd7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPsefr_pEAMvNRyLFKrGSg1eYSUx-7-DU',
    appId: '1:637146499788:ios:652b4c1b427823418b9069',
    messagingSenderId: '637146499788',
    projectId: 'chatterbox-fcd7c',
    storageBucket: 'chatterbox-fcd7c.appspot.com',
    androidClientId: '637146499788-1ajr8lq1p4t4e8n5ucm10e9do969dsjd.apps.googleusercontent.com',
    iosClientId: '637146499788-rknm8ebv19v5fsh5hro31e29eh6b59np.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterbox',
  );
}
